In [3]:
import numpy as np
tensor_2d = np.array([(1,2,3,4), (4,5,6,7), (8,9,10,11), (12,13,14,15)])
print(tensor_2d)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
print(tensor_2d[3][2])

14
