In [0]:
import tensorflow as tf
import numpy as np

In [0]:
matrix1 = np.array([(4, 4, 4), (4, 4, 4), (4, 4, 4)], dtype = 'int32')
matrix2 = np.array([(2, 2, 2), (2, 2, 2), (2, 2, 2)], dtype = 'int32')
print(matrix1, '\n')
print(matrix2)

[[4 4 4]
 [4 4 4]
 [4 4 4]] 

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [0]:
# Произведение
matrix_product = tf.matmul(matrix1, matrix2)

matrix_sum = tf.add(matrix1, matrix2)

# Создание матрицы из чисел с плаваюшей запятой 
matrix3 = np.array([(2, 7, 2), (1, 4, 2), (9, 0, 2)], dtype = 'float32')
print(matrix_product, '\n')
print(matrix_sum, '\n')
print(matrix3)

tf.Tensor(
[[24 24 24]
 [24 24 24]
 [24 24 24]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[6 6 6]
 [6 6 6]
 [6 6 6]], shape=(3, 3), dtype=int32) 

[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]


In [0]:
matrix_det = tf.linalg.det(matrix3)
print(matrix_det)

tf.Tensor(55.999992, shape=(), dtype=float32)
