In [0]:
import numpy as np
import tensorflow as tf
tensor_1d = np.array([1.3, 1, 4.0, 23.99])
print(tensor_1d)

[ 1.3   1.    4.   23.99]


In [0]:
print(tensor_1d[3])

23.99


In [0]:
tensor_2d = np.array([(12, 13, 14, 15), (16, 17, 18, 19), (20, 21, 22, 23), (24, 25, 26, 27)])
print(tensor_2d)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [0]:
print(tensor_2d[2][3])

23


In [0]:
matrix1 = np.array([(3, 3, 3), (3, 3, 3), (3, 3, 3)])
matrix2 = np.array([(4, 4, 4), (4, 4, 4), (4, 4, 4)])
print(matrix1)
print(matrix2)

[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [0]:
sum = tf.add(matrix1, matrix2)
print(sum)

tf.Tensor(
[[7 7 7]
 [7 7 7]
 [7 7 7]], shape=(3, 3), dtype=int64)


In [0]:
subtract = tf.subtract(matrix1, matrix2)
print(subtract)

tf.Tensor(
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]], shape=(3, 3), dtype=int64)


In [0]:
product = tf.matmul(matrix1, matrix2)
print(product)

tf.Tensor(
[[36 36 36]
 [36 36 36]
 [36 36 36]], shape=(3, 3), dtype=int64)
